import { useState } from "react";
import Head from "next/head";
import { Header } from "../components/header/Header";
import { Sidebar } from "../components/sidebar/Sidebar";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  const [showSideBar, setShowSideBar] =  useState(false)

  return (
    <>
      <Head>
        <title>Spotify clon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-spotify-gray min-h-screen text-gray-300">
        <Header setShowSideBar={setShowSideBar}/>
        <Sidebar showSideBar={showSideBar} setShowSideBar={setShowSideBar}/>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
}

export default MyApp;
